- name: retropie
  hosts: all
  become: yes
  
  tasks:
  # ubuntu apt upgrade
    - name: Update apt package list
      become: true
      command: apt update
    
    - name: Upgrade packages
      become: true
      command: apt upgrade -y --allow-downgrades
    
    - name: Autoremove unnecessary packages
      become: true
      command: apt autoremove -y
  
  # retropie upgrade
    - name: git pull RetroPie-Setup
      command: git pull
      args:
        chdir: /home/pi/RetroPie-Setup

    - name: Updating raspbiantools apt_upgrade
      command: sudo __nodialog=1 ./retropie_packages.sh raspbiantools apt_upgrade
      args:
        chdir: /home/pi/RetroPie-Setup

    - name: post_update
      command: sudo __nodialog=1 ./retropie_packages.sh setup post_update
      args:
        chdir: /home/pi/RetroPie-Setup

    - name: update_packages
      command: sudo __nodialog=1 ./retropie_packages.sh setup update_packages
      args:
        chdir: /home/pi/RetroPie-Setup
        
    # retropie configuration
    # nes configuration
    - name: create a file runner_nes.sh
      copy:
        dest: /opt/retropie/configs/nes/runner_nes.sh
        content: |
          #!/bin/bash
          TIMESTAMP=$(date +"%d-%m-%Y_%H-%M-%S")
          /opt/retropie/emulators/retroarch/bin/retroarch \
            -L /opt/retropie/libretrocores/lr-nestopia/nestopia_libretro.so \
            --record "/home/pi/videos/$TIMESTAMP.mp4" \
            --config /opt/retropie/configs/nes/retroarch.cfg "$1"
        mode: '0755'

    - name: reconfigure emulators.cfg for nes
      copy:
        dest: /opt/retropie/configs/nes/emulators.cfg
        content: |
          default = "lr-nestopia"
          lr-nestopia = "/opt/retropie/configs/nes/runner_nes.sh %ROM%"
        mode: '0644'
        force: yes
